[package]
name = "holiday"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
chrono = "0.4"
chrono-tz = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
mysql = "*"